Have the linter flag trailing whitespace and tab characters, which we don't want in the repo (#1096)

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -6,6 +6,23 @@ permissions:
 on: [push, pull_request]
 
 jobs:
+  formatting:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v6
+    - name: Check for trailing whitespace
+      run: |
+        if git grep -InP '[ \t]+$'; then
+          echo "Error: trailing whitespace found on the lines above"
+          exit 1
+        fi
+    - name: Check for tab characters
+      run: |
+        if git grep -InP '\t'; then
+          echo "Error: tab characters found on the lines above"
+          exit 1
+        fi
+
   all-json-valid:
     runs-on: ubuntu-latest
     steps:
